### ISSUE TITLE
Frequent crashes in overworld

### ISSUE THREAD

**Issue by PuddingChef** [Snayff/nqp2#158]
Experiencing frequent crashes in overworld when moving to new nodes.

Log:
`Traceback (most recent call last):
  File "C:\Users\rich2\Documents\nqp2\scripts\__main__.py", line 26, in main
    game_loop(game)
  File "C:\Users\rich2\Documents\nqp2\scripts\__main__.py", line 58, in game_loop
    game.run()
  File "C:\Users\rich2\Documents\nqp2\scripts\core\game.py", line 96, in run
    self.update()
  File "C:\Users\rich2\Documents\nqp2\scripts\core\game.py", line 87, in update
    self.active_scene.update(delta_time)
  File "C:\Users\rich2\Documents\nqp2\scripts\scenes\overworld\scene.py", line 48, in update
    self.ui.update(delta_time)
  File "C:\Users\rich2\Documents\nqp2\scripts\scenes\overworld\ui.py", line 62, in update
    (Direction.LEFT, node_container.lr_node(Direction.LEFT)),
  File "C:\Users\rich2\Documents\nqp2\scripts\scenes\overworld\elements\rings.py", line 239, in lr_node
    current_index = nodes.index(self.selected_node)
ValueError: <scripts.scenes.overworld.elements.node.Node object at 0x000001F74CE75940> is not in list`

**Comment by snayff** [comment]
Overworld no longer exists.
